---
- name: Configure sample server
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars_files:
    - vars/all.yml
  tasks:
    - ansible.builtin.import_tasks: tasks/system.yml
    - ansible.builtin.import_tasks: tasks/php.yml
    - ansible.builtin.import_tasks: tasks/nginx.yml
    - ansible.builtin.import_tasks: tasks/mariadb.yml
    - ansible.builtin.import_tasks: tasks/app.yml
    - ansible.builtin.import_tasks: tasks/dropbox.yml
    - ansible.builtin.import_tasks: tasks/schedules.yml
    - ansible.builtin.import_tasks: tasks/organization.yml
  handlers:
    - ansible.builtin.import_tasks: tasks/handlers.yml