---
- name: Create app schema
  community.mysql.mysql_db:
    name: app
    state: present
    login_user: root
    login_password: "{{ mariadb.root_password }}"
  notify: Import app schema

- name: Create app db user
  community.mysql.mysql_user:
    name: "{{ app.database.user }}"
    password: "{{ app.database.password }}"
    priv: "app.*:ALL,GRANT"
    state: present
    login_user: root
    login_password: "{{ mariadb.root_password }}"

- name: Create app directory
  ansible.builtin.file:
    dest: "{{ system.directories.web_content }}app"
    state: directory

- name: Create app index
  ansible.builtin.copy:
    dest: "{{ system.directories.web_content }}app/index.php"
    content: "<?php phpinfo(); ?>"

- name: Add nginx app server block
  ansible.builtin.template:
    src: etc/nginx/conf.d/app.conf.j2
    dest: "{{ nginx.directories.conf_d }}app.conf"
  notify: Reload nginx
