---
- name: Install mariadb package
  ansible.builtin.package:
    name: mariadb-server
    state: latest

- name: Start and enable mariadb service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- name: Install pymysql python package
  ansible.builtin.pip:
    name: pymysql

- name: Secure mariadb installation
  block:
    - name: Set the root password
      community.mysql.mysql_user:
        name: root
        password: "{{ mariadb.root_password }}"
        login_user: root
        login_unix_socket: /var/lib/mysql/mysql.sock
  
    - name: Copy user-my.cnf file with password credentials.
      ansible.builtin.template:
        src: root/.my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: 0600

    - name: Remove all anonymous user accounts
      community.mysql.mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mariadb.root_password }}"

    - name: Remove the MySQL test database
      community.mysql.mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mariadb.root_password }}"