---
- name: Copy daily backup script
  ansible.builtin.template:
    src: usr/local/bin/database_daily_backup.sh.j2
    dest: "{{system.directories.general_scripts}}database_daily_backup.sh"

- name: Create daily backup schedules
  ansible.builtin.template:
    src: etc/cron.d/database_daily_backup.j2
    dest: "{{ system.directories.cron_configuration }}database_daily_backup"